name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Backend
        run: npx wrangler deploy --env production

      - name: Deploy Frontend
        run: npx wrangler pages deploy frontend/build