name = "agrinetwork-worker"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB"
database_name = "agrinetwork-db"
database_id = "REPLACE_WITH_DB_ID"

[[kv_namespaces]]
binding = "SESSIONS"
id = "REPLACE_WITH_KV_ID"

[[kv_namespaces]]
binding = "RL"
id = "REPLACE_WITH_KV_ID"