name: AI Auto Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint + Prettier (check only)
        run: |
          echo "🔍 Running lint + prettier..."
          npx eslint . || true
          npx prettier --check . || true

      - name: Run Auto Fix (ESLint + Prettier)
        run: |
          echo "🤖 Running AI Auto Debug..."
          npx eslint . --fix || true
          npx prettier --write . || true
          echo "✅ Auto fixes applied"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 AI Auto Debug: auto-fix lint/prettier issues"
            git push
          fi