name: AI Auto Debug

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint + Prettier
        run: npm run lint || echo "Lint failed"

      - name: Run Tests
        run: npm test || echo "Tests failed"

      - name: Run AI Debug Script
        run: node scripts/ai-debug.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}